config/routes.rb
CritiqueMe::Application.routes.draw do
  namespace :admin do
    # biz logic
    resources :categories do
      put 'deactivate', :on => :member
      put 'activate', :on => :member
    end
    resources :default_questions do
      put 'deactivate', :on => :member
      put 'activate', :on => :member
    end
    resources :questions do
      put 'deactivate', :on => :member
      put 'activate', :on => :member
    end
    resources :questionnaires do
      put 'deactivate', :on => :member
      put 'activate', :on => :member
    end
    resources :canned_questions do
      put 'deactivate', :on => :member
      put 'activate', :on => :member
    end
    resources :flagged_questions do
      put 'hide', :on => :member
    end
  end

  match '/privacy_options',                 :to => 'dashboard#privacy_options', :as => :privacy_options
  match '/email_preferences',               :to => 'dashboard#email_preferences', :as => :email_preferences

  match '/question/:id',                    :to => 'questions#question',        :as => :question
  match '/q/:token/:question_id',           :to => 'referral#incoming',         :as => :question_referral
  match '/questions',                       :to => 'questions#new_question',    :as => :questions
  match '/new_question',                    :to => 'questions#new_question',    :as => :new_question
  match '/edit_question/:id',               :to => 'questions#edit_question',   :as => :edit_question
  match '/choose_question(/:id)',           :to => 'questions#choose_question', :as => :choose_question
  match '/category(/:category_id)',         :to => 'questions#choose_question', :as => :category
  match '/questionnaire/:id',               :to => 'questions#questionnaire',   :as => :questionnaire
  match '/post_to_graph/:id',               :to => 'questions#post_to_graph',   :as => :post_to_graph
  match '/canned_answer/:id',               :to => 'answers#canned_answer',     :as => :canned_answer
  match '/flag_question',                   :to => 'questions#flag',            :as => :new_flag
  match '/toggle_pitch_dlg',                :to => 'questions#toggle_pitch_dlg',:as => :toggle_pitch_dlg

  match '/answer/new',                      :to => 'answers#new',               :as => :new_answer

  match '/path_answer',                     :to => 'welcome#path_answer',       :as => :path_answer
  match '/path_canned_finished',            :to => 'welcome#canned_finished',   :as => :path_canned_finished
  match '/path_choose_question',            :to => 'welcome#choose_question',   :as => :path_choose_question
  match '/path_write_question',             :to => 'welcome#write_question',    :as => :path_write_question
  match '/path_manual_share',               :to => 'welcome#manual_share',      :as => :path_manual_share

  match '/share/:question_id',              :to => 'share#index',               :as => :share
  match '/manual_share',                    :to => 'share#manual_share',        :as => :manual_share
  match '/get_contacts',                    :to => 'share#get_contacts',        :as => :get_contacts
  match '/share_contacts',                  :to => 'share#share_contacts',      :as => :share_contacts
  match '/share_friends',                   :to => 'share#share_friends',       :as => :share_friends
  match '/share_question/:id',              :to => 'share#three_options',       :as => :share_question

  match '/about_us',                        :to => 'corporate#about_us',        :as => :about_us
  match '/faq',                             :to => 'corporate#faq',             :as => :faq
  match '/contact_us',                      :to => 'corporate#contact_us',      :as => :contact_us
  match '/tos',                             :to => 'corporate#tos',             :as => :tos
  match '/privacy',                         :to => 'corporate#privacy',         :as => :privacy

  # override the splash path
  match '/splash',                          :to => 'welcome#path',              :as => :splash

  root :to => "questions#choose_question"
end

app/controllers/dashboard_controller.rb
Rails::Engine.mixin __FILE__
class DashboardController < ApplicationController
  layout "cm2"

  def index
    Time.zone = "Central Time (US & Canada)"
    @collection_filter = params['coll'] || "questions"
    @per_page = 10
    if @collection_filter == "questions"
      scope = @user.questions.where(:active => true, :canned_question_id => nil).order("created_at DESC")
    else
      scope = @user.answers.joins('JOIN questions ON answers.question_id=questions.id').
          where('questions.canned_question_id IS NULL').order("created_at DESC")
    end
    @num_records = scope.count
    @collection = scope.paginate(:page => params['page'], :per_page => @per_page)
    @last_five_questions = DefaultQuestion.active.featured.order('last_asked_at DESC')
  end

  def email_preferences
    if params['user']
      @user.update_attributes params['user']
      if @user.valid?
        flash[:profile_updated] = "Your email preferences have been updated."
      end
    end
  end

end

app/views/dashboard/_answer_line_item.html.haml
%tr
  %td.question_item
    = link_to answer.question.question_text_pretty, question_path(answer.question)
    %br
    Posted on:
    %span.light= answer.question.created_at.strftime "%-m/%-d/%Y %I:%M %p"
  /%td.see_answers= link_to image_tag("/assets/dashboard/invite_friends.jpg")

app/views/dashboard/_dash_nav.html.haml
.span-24#dash_nav
  %ul
    - if params['controller'] == "dashboard"
      %li.selected= link_to "Dashboard", dashboard_path
    - else
      %li= link_to "Dashboard", dashboard_path

    - if params['controller'] == 'questions'
      %li.selected= link_to "Questions", questions_path
    - else
      %li= link_to "Questions", questions_path

app/views/dashboard/_dash_sidebar.html.haml
#dash_sidebar
  - if defined?(@user.avatar)
    #avatar= image_tag(@user.avatar.url ? @user.avatar.normal.url : "/assets/dashboard/default_avatar.jpg")
    #change_avatar
      .buttons= button_to "Change Photo", '#'
    #sub_avatar
      %em.quiet Photos should be less than 1MB in size.
  #profile_nav
    %h4 Profile Settings
    %ul
      - if params['action'] == "your_profile"
        %li.selected.loud Your Profile &raquo;
      - else
        %li= link_to "Your Profile", your_profile_path

      - if params['action'] == "privacy_options"
        %li.selected.loud Privacy Options &raquo;
      - else
        %li= link_to "Privacy Options", privacy_options_path

      - if params['action'] == "change_password"
        %li.selected.loud Change Password &raquo;
      - else
        %li= link_to "Change Password", change_password_path

app/views/dashboard/_question_line_item.html.haml
%tr
  %td.question_item
    = link_to question.question_text_pretty, question_path(question)
    %br
    Posted on:
    %span.quiet= question.created_at.strftime "%-m/%-d/%Y %I:%M %p"
  - if question.answers.count < 5
    %td.invite_friends
      =# link_to image_tag("questions/invite_friends_button.png"), '#', :data => {'question-id' => question.id}
      = link_to image_tag("questions/invite_friends_button.png"), share_question_path(question)
  - else
    %td.see_answers
      = link_to image_tag("questions/see_answers_button.png"), question_path(question)

app/views/dashboard/_user_form.html.haml
= semantic_form_for @user, :url => your_profile_path do |f|
  = f.inputs do
    = f.input :first_name, :label => "First Name"
    = f.input :last_name, :label => "Last Name"
    = f.input :email, :label => "Email Address"
    = f.input :birthday, :order => [:month, :day, :year], :start_year => 1920, :end_year => 2000, :prompt => {:day => "Day", :month => "Month", :year => "Year"}, :include_blank => false
    .clearer
    = f.input :zip
    = f.input :gender, :label => "Gender", :as => :select, :collection => [["Female", "f"], ["Male", "m"]]
  = f.actions do
    = f.action :submit, :label => "Update"

app/views/dashboard/change_password.html.haml
- content_for :extra_css do
  = stylesheet_link_tag "dashboard/cm_change_password"

.cm_content

  .inner_content
    .inner_nav
      .under.fuzzy#your_profile= link_to "My Profile", your_profile_path
      .under.fuzzy#privacy_options= link_to "Privacy Options", privacy_options_path
      .over.fuzzy#change_pass Change Password


    .qcontainer.fuzzy
      = show_flash(flash)
      %fieldset.form_box
        .hdr
          %p Change Password
        = semantic_form_for @user, :url => change_password_path do |f|
          = f.inputs do
            - if @password_error
              %li.error.inline-errors= @password_error
            = f.input :password, :label => "Old Password"
            = f.input :new_password, :label => "New Password"
            = f.input :new_password_confirmation, :label => "Confirm Password"
          = f.actions do
            = f.action :submit, :label => "Save Changes"

app/views/dashboard/email_preferences.html.haml
- content_for :extra_css do
  = stylesheet_link_tag "questions/new_question"
  = stylesheet_link_tag "dashboard/cm_profile_edit"

.grad_bg
  .cm_content

    .inner_content
      .inner_nav
        .over.fuzzy#your_profile My Profile

      .qcontainer.fuzzy
        = show_flash(flash)
        %fieldset.form_box.email_prefs
          .hdr
            %p Email Preferences
          = semantic_form_for @user, :url => email_preferences_path do |f|
            = f.inputs do
              = f.input :email_preferences, :label => "", :as => :radio, :collection => [['No Restrictions', 0], ['Receive emails from us no more than once a week', 1], ['Unsubscribe from third party promotions', 2], ['Unsubscribe from all emails', 3]]
            = f.actions do
              = f.action :submit, :label => "Update"

- content_for :extra_javascripts do
  = javascript_include_tag "dashboard/email_preferences"
  = javascript_include_tag "questions/resize_cm_content"

app/views/dashboard/forgot_password.html.haml
- content_for :extra_css do
  = stylesheet_link_tag "questions/new_question"
  = stylesheet_link_tag "dashboard/forgot_password"
  = stylesheet_link_tag "dashboard/cm_sign_in"

.grad_bg
  .cm_content
    .inner_content
      .qcontainer.fuzzy.all_round.gateway#forgot_pass
        .form_hdr Enter the email address you used to register and we'll send <br />you an email to retrieve your password.
        = semantic_form_for @user, :url => forgot_password_path do |f|
          = f.inputs do
            - if flash[:password_success]
              #success= flash[:password_success]
            = f.input :email, :label => "Email Address"
            - if flash[:email_error]
              .error.inline-errors= flash[:email_error]
            .clearer
          = f.actions do
            = f.action :submit, :label => "Submit"
        .form_sub If you didn't get any mail then please contact #{mail_to SEED_BLOCKS_ENGINE_CONFIG[:default_from_address]} for assistance.


- content_for :extra_javascripts do
  = javascript_include_tag "questions/resize_cm_content"

app/views/dashboard/index.html.haml
- content_for :extra_css do
  = stylesheet_link_tag "share/share"
  = stylesheet_link_tag "dashboard/index"
  = stylesheet_link_tag "questions/new_question"
  = stylesheet_link_tag "path_pages/share/three_options"

.grad_bg
  .cm_content
    .inner_content
      .inner_nav
        - if @collection_filter == "questions"
          .over.fuzzy#questions_posted Questions Posted
          .under.fuzzy#answers_posted= link_to "Answers Given", dashboard_path(:coll => "answers")
        - else
          .under.fuzzy#questions_posted= link_to "Questions Posted", dashboard_path(:coll => "questions")
          .over.fuzzy#answers_posted Answers Given
      .qs_asked_today.fuzzy= render :partial => "questions/asked_today"
      .qcontainer.fuzzy

        %table#dashtable{:data => {:page => params['page'] || 1, :num_questions => @num_records, :per_page => @per_page}}
          %tbody
            - if @collection_filter == "questions"
              - if @collection.empty?
                %tr
                  %td.none_posted
                    No Questions posted yet.  #{link_to "Post one now!", choose_question_path}
              - else
                = render :partial => "question_line_item", :collection => @collection, :as => :question
            - else
              - if @collection.empty?
                %tr
                  %td.none_posted
                    No Answers given yet.
              - else
                = render :partial => "answer_line_item", :collection => @collection, :as => :answer
          %tfoot
            %tr
              %td{:colspan => 2}= will_paginate @collection, :page_links => false, :previous_label => "Back", :next_label => "Next"



- @collection.each do |o|
  - if @collection_filter == 'questions'
    - if o.photo.url
      .qimg_dlg{:id => "qimg_dialog_#{o.id}"}= image_tag o.photo.url
  - else
    - if o.question.photo.url
      .qimg_dlg{:id => "qimg_dialog_#{o.question_id}"}= image_tag o.question.photo.url

- content_for :extra_javascripts do
  = javascript_include_tag "dashboard/inviter"
  = javascript_include_tag "dashboard/dash_index"
  = javascript_include_tag "questions/canned"
  = javascript_include_tag "questions/resize_cm_content"

app/views/dashboard/privacy_options.html.haml
- content_for :extra_css do
  = stylesheet_link_tag "dashboard/privacy_options"


.cm_content

  .inner_content
    .inner_nav
      .under.fuzzy#your_profile= link_to "My Profile", your_profile_path
      .over.fuzzy#privacy_options Privacy Options
      .under.fuzzy#change_pass= link_to "Change Password", change_password_path


    .qcontainer.fuzzy
      = show_flash(flash)
      %fieldset.form_box
        .hdr
          %p Privacy Options
        = semantic_form_for @user, :url => privacy_options_path do |f|
          = f.inputs do
            = f.input :privacy_ask_questions, :label => "Who can send you questions?", :as => :radio, :collection => [["Anyone can ask you questions.", 0], ["Only CritiqueMe members with name and photos can ask you questions.", 1]]
          = f.actions do
            = f.action :submit, :label => "Save Changes"


- content_for :extra_javascripts do
  = javascript_include_tag "dashboard/privacy_options"

app/views/dashboard/reset_password.html.haml
- content_for :extra_css do
  = stylesheet_link_tag "questions/new_question"
  = stylesheet_link_tag "dashboard/forgot_password"
  = stylesheet_link_tag "dashboard/cm_sign_in"

.grad_bg
  .cm_content
    .inner_content
      .qcontainer.fuzzy.all_round.gateway#forgot_pass
        .form_hdr Enter a new password.  You'll be immediately logged in to your account.
        = semantic_form_for @user, :url => reset_password_path do |f|
          = f.inputs do
            = f.input :password, :label => "New Password"
            .clearer
            - if flash[:password_error]
              .error.inline-errors= flash[:password_error]
          = f.actions do
            = f.action :submit, :label => "Update"




- content_for :extra_javascripts do
  = javascript_include_tag "questions/resize_cm_content"

app/views/dashboard/sign_in.html.haml
- content_for :extra_css do
  = stylesheet_link_tag "questions/new_question"
  = stylesheet_link_tag "dashboard/cm_sign_in"

.grad_bg
  .cm_content
    .inner_content
      .qcontainer.fuzzy.all_round.gateway#signup

        .form_hdr Sign in with your email address and password:
        = semantic_form_for @user, :url => sign_in_path do |f|
          = f.inputs do
            = f.input :email, :label => "Email Address"
            = f.input :password
            .clearer
            - if flash[:sign_in_error]
              .error.inline-errors= flash[:sign_in_error]
            #forgotter= link_to "Forgot Password?", forgot_password_path
          = f.actions do
            = f.action :submit, :label => "Sign In"

- content_for :extra_javascripts do
  = javascript_include_tag "dashboard/sign_in"
  = javascript_include_tag "questions/resize_cm_content"

app/views/dashboard/your_profile.html.haml
- content_for :extra_css do
  = stylesheet_link_tag "questions/new_question"
  = stylesheet_link_tag "dashboard/cm_profile_edit"

.grad_bg
  .cm_content
    .inner_content
      .inner_nav
        .over.fuzzy#your_profile My Profile

      .qcontainer.fuzzy
        = show_flash(flash)
        %fieldset.form_box
          .hdr
            %p My Private Information
          %p= link_to "Email Preferences", email_preferences_path
          = render :partial => "user_form"

- content_for :extra_javascripts do
  = javascript_include_tag "questions/resize_cm_content"