config/routes.rb
CritiqueMe::Application.routes.draw do
  namespace :admin do
    # biz logic
    resources :categories do
      put 'deactivate', :on => :member
      put 'activate', :on => :member
    end
    resources :default_questions do
      put 'deactivate', :on => :member
      put 'activate', :on => :member
    end
    resources :questions do
      put 'deactivate', :on => :member
      put 'activate', :on => :member
    end
    resources :questionnaires do
      put 'deactivate', :on => :member
      put 'activate', :on => :member
    end
    resources :canned_questions do
      put 'deactivate', :on => :member
      put 'activate', :on => :member
    end
    resources :flagged_questions do
      put 'hide', :on => :member
    end
  end

  match '/privacy_options',                 :to => 'dashboard#privacy_options', :as => :privacy_options
  match '/email_preferences',               :to => 'dashboard#email_preferences', :as => :email_preferences

  match '/question/:id',                    :to => 'questions#question',        :as => :question
  match '/q/:token/:question_id',           :to => 'referral#incoming',         :as => :question_referral
  match '/questions',                       :to => 'questions#new_question',    :as => :questions
  match '/new_question',                    :to => 'questions#new_question',    :as => :new_question
  match '/edit_question/:id',               :to => 'questions#edit_question',   :as => :edit_question
  match '/choose_question(/:id)',           :to => 'questions#choose_question', :as => :choose_question
  match '/category(/:category_id)',         :to => 'questions#choose_question', :as => :category
  match '/questionnaire/:id',               :to => 'questions#questionnaire',   :as => :questionnaire
  match '/post_to_graph/:id',               :to => 'questions#post_to_graph',   :as => :post_to_graph
  match '/canned_answer/:id',               :to => 'answers#canned_answer',     :as => :canned_answer
  match '/flag_question',                   :to => 'questions#flag',            :as => :new_flag
  match '/toggle_pitch_dlg',                :to => 'questions#toggle_pitch_dlg',:as => :toggle_pitch_dlg

  match '/answer/new',                      :to => 'answers#new',               :as => :new_answer

  match '/path_answer',                     :to => 'welcome#path_answer',       :as => :path_answer
  match '/path_canned_finished',            :to => 'welcome#canned_finished',   :as => :path_canned_finished
  match '/path_choose_question',            :to => 'welcome#choose_question',   :as => :path_choose_question
  match '/path_write_question',             :to => 'welcome#write_question',    :as => :path_write_question
  match '/path_manual_share',               :to => 'welcome#manual_share',      :as => :path_manual_share

  match '/share/:question_id',              :to => 'share#index',               :as => :share
  match '/manual_share',                    :to => 'share#manual_share',        :as => :manual_share
  match '/get_contacts',                    :to => 'share#get_contacts',        :as => :get_contacts
  match '/share_contacts',                  :to => 'share#share_contacts',      :as => :share_contacts
  match '/share_friends',                   :to => 'share#share_friends',       :as => :share_friends
  match '/share_question/:id',              :to => 'share#three_options',       :as => :share_question

  match '/about_us',                        :to => 'corporate#about_us',        :as => :about_us
  match '/faq',                             :to => 'corporate#faq',             :as => :faq
  match '/contact_us',                      :to => 'corporate#contact_us',      :as => :contact_us
  match '/tos',                             :to => 'corporate#tos',             :as => :tos
  match '/privacy',                         :to => 'corporate#privacy',         :as => :privacy

  # override the splash path
  match '/splash',                          :to => 'welcome#path',              :as => :splash

  root :to => "questions#choose_question"
end

app/models/canned_question.rb
class CannedQuestion < ActiveRecord::Base
  has_many :questions
  belongs_to :category

  scope :active, where(:active => true)

  validates :category_id, :presence => true
  #validates :question_id, :presence => true
end

app/controllers/admin/canned_questions_controller.rb
class Admin::CannedQuestionsController < Admin::SbAdminController
  actions :index, :show, :new, :edit, :create, :update, :deactivate, :activate

  def new
    @canned_question = CannedQuestion.new
  end

  def create
    create!(:notice => "Canned Question Created"){ admin_canned_questions_path }
  end

  def deactivate
    @canned_question = CannedQuestion.where(:id => params['id']).first
    @canned_question.update_attribute :active, false
    flash[:notice] = "Canned Question Deactivated"
    redirect_to admin_canned_questions_path
  end

  def activate
    @canned_question = CannedQuestion.where(:id => params['id']).first
    @canned_question.update_attribute :active, true
    flash[:notice] = "Canned Question Activated"
    redirect_to admin_canned_questions_path
  end

  protected

  def collection
    @canned_questions ||= end_of_association_chain.order('id DESC').paginate(:page => params[:page])
  end
end

app/views/admin/canned_questions/_canned_question.html.haml
%tr{:class => cycle('odd', 'even')}
  %td.question= link_to canned_question.text, admin_canned_question_path(canned_question)
  %td= canned_question.num_choices
  %td.active
    %small= canned_question.active ? 'Active' : 'Inactive'
  %td.actions
    = image_tag 'admin/icons/tool.png', :class => 'tools', 'data-menu' => "#menu_canned_question_#{canned_question.id}"
    %ul[canned_question, :menu]
      %li= link_to 'Show', admin_canned_question_path(canned_question), :class => 'show'
      %li= link_to 'Edit', edit_admin_canned_question_path(canned_question), :class => 'edit'
      %li
        - if canned_question.active?
          = link_to 'Deactivate', deactivate_admin_canned_question_path(canned_question), :class => 'deactivate', :method => :put
        - else
          = link_to 'Activate', activate_admin_canned_question_path(canned_question), :class => 'activate', :method => :put

app/views/admin/canned_questions/_form.html.haml
= semantic_form_for @canned_question, :url => url do |f|
  = f.inputs do
    = f.input :category, :prompt => "Choose a category", :collection => Category.for_select
    = f.input :text, :as => :string, :label => "Question"
    = f.input :num_choices, :as => :number, :label => "Number of Friend Choices"
    .clearer
  = f.actions do
    - if @canned_question.new_record?
      = f.action :submit, :label => "Create Canned Question"
    - else
      = f.action :submit, :label => "Edit Canned Question"

app/views/admin/canned_questions/edit.html.haml
= content_for :side_menu do
  %ol.nav
    %li
      = link_to "&laquo; All Questions".html_safe, admin_canned_questions_path
      = link_to "&laquo; This Question".html_safe, admin_canned_question_path(@canned_question)

%h1 Edit Canned Question

= render :partial => "form", :locals => {:url => admin_canned_question_path(@canned_question)}

app/views/admin/canned_questions/index.html.haml
= content_for :side_menu do
  %ol.nav
    %li
      = link_to "New Question &raquo;".html_safe, new_admin_canned_question_path

%h1
  CritiqueMe Canned Questions

%table.merchants.smoothness.highlighter
  %thead
    %tr
      %th Question
      %th Num Friends
      %th &nbsp;
      %th &nbsp;
  %tfoot
    %tr
      %td{:colspan => 6}
        = will_paginate
  %tbody
    - if @canned_questions.empty?
      %tr
        %td{:colspan => 6}
          %em No canned questions found.
    - else
      = render @canned_questions

app/views/admin/canned_questions/new.html.haml
%h1 Create a New Canned Question

= render :partial => "form", :locals => {:url => admin_canned_questions_path}

app/views/admin/canned_questions/show.html.haml
= content_for :side_menu do
  %ol.nav
    %li
      = link_to "&laquo; All Questions".html_safe, admin_canned_questions_path
      = link_to "Edit Question &raquo;".html_safe, edit_admin_canned_question_path(@canned_question)
      - if @canned_question.active?
        = link_to "Deactivate &raquo;".html_safe, deactivate_admin_canned_question_path(@canned_question), :method => :put
      - else
        = link_to "Activate &raquo;".html_safe, activate_admin_canned_question_path(@canned_question), :method => :put

%h1 Show Canned Question

%ul.show_page
  %li
    %label Category:
    %p
      - if @canned_question.category
        = link_to @canned_question.category.name, admin_category_path(@canned_question.category)
      - else
        None
    .clear
  %li
    %label Question Text:
    %p= @canned_question.text
    .clear
  %li
    %label Num Friends:
    %p= @canned_question.num_choices
    .clear
  %li
    %label Active?:
    %p= @canned_question.active ? "Active" : "Inactive"
    .clear