config/routes.rb
CritiqueMe::Application.routes.draw do
  namespace :admin do
    # biz logic
    resources :categories do
      put 'deactivate', :on => :member
      put 'activate', :on => :member
    end
    resources :default_questions do
      put 'deactivate', :on => :member
      put 'activate', :on => :member
    end
    resources :questions do
      put 'deactivate', :on => :member
      put 'activate', :on => :member
    end
    resources :questionnaires do
      put 'deactivate', :on => :member
      put 'activate', :on => :member
    end
    resources :canned_questions do
      put 'deactivate', :on => :member
      put 'activate', :on => :member
    end
    resources :flagged_questions do
      put 'hide', :on => :member
    end
  end

  match '/privacy_options',                 :to => 'dashboard#privacy_options', :as => :privacy_options
  match '/email_preferences',               :to => 'dashboard#email_preferences', :as => :email_preferences

  match '/question/:id',                    :to => 'questions#question',        :as => :question
  match '/q/:token/:question_id',           :to => 'referral#incoming',         :as => :question_referral
  match '/questions',                       :to => 'questions#new_question',    :as => :questions
  match '/new_question',                    :to => 'questions#new_question',    :as => :new_question
  match '/edit_question/:id',               :to => 'questions#edit_question',   :as => :edit_question
  match '/choose_question(/:id)',           :to => 'questions#choose_question', :as => :choose_question
  match '/category(/:category_id)',         :to => 'questions#choose_question', :as => :category
  match '/questionnaire/:id',               :to => 'questions#questionnaire',   :as => :questionnaire
  match '/post_to_graph/:id',               :to => 'questions#post_to_graph',   :as => :post_to_graph
  match '/canned_answer/:id',               :to => 'answers#canned_answer',     :as => :canned_answer
  match '/flag_question',                   :to => 'questions#flag',            :as => :new_flag
  match '/toggle_pitch_dlg',                :to => 'questions#toggle_pitch_dlg',:as => :toggle_pitch_dlg

  match '/answer/new',                      :to => 'answers#new',               :as => :new_answer

  match '/path_answer',                     :to => 'welcome#path_answer',       :as => :path_answer
  match '/path_canned_finished',            :to => 'welcome#canned_finished',   :as => :path_canned_finished
  match '/path_choose_question',            :to => 'welcome#choose_question',   :as => :path_choose_question
  match '/path_write_question',             :to => 'welcome#write_question',    :as => :path_write_question
  match '/path_manual_share',               :to => 'welcome#manual_share',      :as => :path_manual_share

  match '/share/:question_id',              :to => 'share#index',               :as => :share
  match '/manual_share',                    :to => 'share#manual_share',        :as => :manual_share
  match '/get_contacts',                    :to => 'share#get_contacts',        :as => :get_contacts
  match '/share_contacts',                  :to => 'share#share_contacts',      :as => :share_contacts
  match '/share_friends',                   :to => 'share#share_friends',       :as => :share_friends
  match '/share_question/:id',              :to => 'share#three_options',       :as => :share_question

  match '/about_us',                        :to => 'corporate#about_us',        :as => :about_us
  match '/faq',                             :to => 'corporate#faq',             :as => :faq
  match '/contact_us',                      :to => 'corporate#contact_us',      :as => :contact_us
  match '/tos',                             :to => 'corporate#tos',             :as => :tos
  match '/privacy',                         :to => 'corporate#privacy',         :as => :privacy

  # override the splash path
  match '/splash',                          :to => 'welcome#path',              :as => :splash

  root :to => "questions#choose_question"
end

app/models/questionnaire.rb
# == Schema Information
#
# Table name: questionnaires
#
#  id   :integer(4)      not null, primary key
#  name :string(255)
#

class Questionnaire < ActiveRecord::Base
  has_many :default_questions

  scope :active, where(:active => true)
end

app/controllers/admin/questionnaires_controller.rb
class Admin::QuestionnairesController < Admin::SbAdminController
  actions :index, :show, :new, :edit, :create, :update, :deactivate, :activate

  def create
    create!(:notice => "Questionnaire Created"){ admin_questionnaires_path }
  end

  def deactivate
    @questionnaire = Questionnaire.where(:id => params['id']).first
    @questionnaire.update_attribute :active, false
    flash[:notice] = "Questionnaire Deactivated"
    redirect_to admin_questionnaires_path
  end

  def activate
    @questionnaire = Questionnaire.where(:id => params['id']).first
    @questionnaire.update_attribute :active, true
    flash[:notice] = "Questionnaire Activated"
    redirect_to admin_questionnaires_path
  end

  protected

  def collection
    @questionnaires ||= end_of_association_chain.paginate(:page => params[:page])
  end
end

app/views/admin/questionnaires/_form.html.haml
= semantic_form_for @questionnaire, :url => url do |f|
  = f.inputs do
    = f.input :name
    .clearer

  = f.actions do
    - if @questionnaire.new_record?
      = f.action :submit, :label => "Create Questionnaire"
    - else
      = f.action :submit, :label => "Edit Questionnaire"

app/views/admin/questionnaires/_questionnaire.html.haml
%tr{:class => cycle('odd', 'even')}
  %td.name= link_to questionnaire.name, admin_questionnaire_path(questionnaire)
  %td.count= number_with_delimiter questionnaire.default_questions.count
  %td.active
    %small= questionnaire.active ? 'Active' : 'Inactive'
  %td.actions
    = image_tag 'admin/icons/tool.png', :class => 'tools', 'data-menu' => "#menu_questionnaire_#{questionnaire.id}"
    %ul[questionnaire, :menu]
      %li= link_to 'Show', admin_questionnaire_path(questionnaire), :class => 'show'
      %li= link_to 'Edit', edit_admin_questionnaire_path(questionnaire), :class => 'edit'
      %li
        - if questionnaire.active?
          = link_to 'Deactivate', deactivate_admin_questionnaire_path(questionnaire), :class => 'deactivate', :method => :put
        - else
          = link_to 'Activate', activate_admin_questionnaire_path(questionnaire), :class => 'activate', :method => :put

app/views/admin/questionnaires/edit.html.haml
= content_for :side_menu do
  %ol.nav
    %li
      = link_to "&laquo; All".html_safe, admin_questionnaires_path
      = link_to "&laquo; Show".html_safe, admin_questionnaire_path(@questionnaire)

%h1 Edit Questionnaire

= render :partial => "form", :locals => {:url => admin_questionnaire_path(@questionnaire)}

app/views/admin/questionnaires/index.html.haml
= content_for :side_menu do
  %ol.nav
    %li
      = link_to "Create New &raquo;".html_safe, new_admin_questionnaire_path

%h1
  CritiqueMe Questionnaires

%table.merchants.smoothness.highlighter
  %thead
    %tr
      %th Questionnaire
      %th Num Questions
      %th &nbsp;
      %th &nbsp;
  %tfoot
    %tr
      %td{:colspan => 6}
        = will_paginate
  %tbody
    - if @questionnaires.empty?
      %tr
        %td{:colspan => 4}
          %em No questionnaires found.  #{link_to "Create one now &raquo;".html_safe, new_admin_questionnaire_path}
    - else
      = render @questionnaires

app/views/admin/questionnaires/new.html.haml
%h1 Create a New Questionnaire

= render :partial => "form", :locals => {:url => admin_questionnaires_path}

app/views/admin/questionnaires/show.html.haml
= content_for :side_menu do
  %ol.nav
    %li
      = link_to "&laquo; All".html_safe, admin_questionnaires_path
      = link_to "Edit &raquo;".html_safe, edit_admin_questionnaire_path(@questionnaire)
      - if @questionnaire.active?
        = link_to "Deactivate &raquo;".html_safe, deactivate_admin_questionnaire_path(@questionnaire), :method => :put
      - else
        = link_to "Activate &raquo;".html_safe, activate_admin_questionnaire_path(@questionnaire), :method => :put

%h1 Show Questionnaire

%ul.show_page
  %li
    %label Name:
    %p= @questionnaire.name
    .clear
  %li
    %label Active?:
    %p= @questionnaire.active ? "Active" : "Inactive"
    .clear
  %li
    %label Questions:
    %p
      - if @questionnaire.default_questions.empty?
        No questions yet.  #{link_to "Add one now &raquo;".html_safe, new_admin_default_question_path(:questionnaire_id => @questionnaire.id)}
      - else
        - @questionnaire.default_questions.each_with_index do |q, i|
          = "#{i+1}) #{link_to q.question_text, admin_default_question_path(q)}".html_safe
          %br
        %br
        = link_to "Add another question &raquo;".html_safe, new_admin_default_question_path(:questionnaire_id => @questionnaire.id)
    .clear