config/routes.rb
CritiqueMe::Application.routes.draw do
  namespace :admin do
    # biz logic
    resources :categories do
      put 'deactivate', :on => :member
      put 'activate', :on => :member
    end
    resources :default_questions do
      put 'deactivate', :on => :member
      put 'activate', :on => :member
    end
    resources :questions do
      put 'deactivate', :on => :member
      put 'activate', :on => :member
    end
    resources :questionnaires do
      put 'deactivate', :on => :member
      put 'activate', :on => :member
    end
    resources :canned_questions do
      put 'deactivate', :on => :member
      put 'activate', :on => :member
    end
    resources :flagged_questions do
      put 'hide', :on => :member
    end
  end

  match '/privacy_options',                 :to => 'dashboard#privacy_options', :as => :privacy_options
  match '/email_preferences',               :to => 'dashboard#email_preferences', :as => :email_preferences

  match '/question/:id',                    :to => 'questions#question',        :as => :question
  match '/q/:token/:question_id',           :to => 'referral#incoming',         :as => :question_referral
  match '/questions',                       :to => 'questions#new_question',    :as => :questions
  match '/new_question',                    :to => 'questions#new_question',    :as => :new_question
  match '/edit_question/:id',               :to => 'questions#edit_question',   :as => :edit_question
  match '/choose_question(/:id)',           :to => 'questions#choose_question', :as => :choose_question
  match '/category(/:category_id)',         :to => 'questions#choose_question', :as => :category
  match '/questionnaire/:id',               :to => 'questions#questionnaire',   :as => :questionnaire
  match '/post_to_graph/:id',               :to => 'questions#post_to_graph',   :as => :post_to_graph
  match '/canned_answer/:id',               :to => 'answers#canned_answer',     :as => :canned_answer
  match '/flag_question',                   :to => 'questions#flag',            :as => :new_flag
  match '/toggle_pitch_dlg',                :to => 'questions#toggle_pitch_dlg',:as => :toggle_pitch_dlg

  match '/answer/new',                      :to => 'answers#new',               :as => :new_answer

  match '/path_answer',                     :to => 'welcome#path_answer',       :as => :path_answer
  match '/path_canned_finished',            :to => 'welcome#canned_finished',   :as => :path_canned_finished
  match '/path_choose_question',            :to => 'welcome#choose_question',   :as => :path_choose_question
  match '/path_write_question',             :to => 'welcome#write_question',    :as => :path_write_question
  match '/path_manual_share',               :to => 'welcome#manual_share',      :as => :path_manual_share

  match '/share/:question_id',              :to => 'share#index',               :as => :share
  match '/manual_share',                    :to => 'share#manual_share',        :as => :manual_share
  match '/get_contacts',                    :to => 'share#get_contacts',        :as => :get_contacts
  match '/share_contacts',                  :to => 'share#share_contacts',      :as => :share_contacts
  match '/share_friends',                   :to => 'share#share_friends',       :as => :share_friends
  match '/share_question/:id',              :to => 'share#three_options',       :as => :share_question

  match '/about_us',                        :to => 'corporate#about_us',        :as => :about_us
  match '/faq',                             :to => 'corporate#faq',             :as => :faq
  match '/contact_us',                      :to => 'corporate#contact_us',      :as => :contact_us
  match '/tos',                             :to => 'corporate#tos',             :as => :tos
  match '/privacy',                         :to => 'corporate#privacy',         :as => :privacy

  # override the splash path
  match '/splash',                          :to => 'welcome#path',              :as => :splash

  root :to => "questions#choose_question"
end

app/models/default_question.rb
# == Schema Information
#
# Table name: default_questions
#
#  id               :integer(4)      not null, primary key
#  category_id      :integer(4)
#  questionnaire_id :integer(4)
#  question_type    :integer(4)      default(0)
#  question_text    :text
#  active           :boolean         default(true)
#

class DefaultQuestion < ActiveRecord::Base
  belongs_to :category
  belongs_to :questionnaire
  has_many :default_multiple_choice_options
  accepts_nested_attributes_for :default_multiple_choice_options

  validates_presence_of :category_id, :question_text, :question_type, :message => "Required"

  scope :active, where(:active => true)
  scope :not_in_questionnaire, where(:questionnaire_id => nil)
  scope :prioritized, order('priority DESC')
  scope :featured, where(:featured => true)
  scope :random, order('RAND()')

  private

end

app/controllers/admin/default_questions_controller.rb
class Admin::DefaultQuestionsController < Admin::SbAdminController
  actions :index, :show, :new, :edit, :create, :update, :deactivate, :activate

  def new
    @default_question = DefaultQuestion.new(:questionnaire_id => params['questionnaire_id'])
  end

  def create
    # strip out the multi choice options if the question isn't a multi choice question (prevents validation errors)
    unless params['default_question']['question_type'] == Question::QUESTION_TYPES.index(:multiple_choice).to_s
      params['default_question'].delete('default_multiple_choice_options_attributes')
    end
    create!(:notice => "Default Question Created"){ admin_default_questions_path }
  end

  def deactivate
    @default_question = DefaultQuestion.where(:id => params['id']).first
    @default_question.update_attribute :active, false
    flash[:notice] = "Default Question Deactivated"
    redirect_to admin_default_questions_path
  end

  def activate
    @default_question = DefaultQuestion.where(:id => params['id']).first
    @default_question.update_attribute :active, true
    flash[:notice] = "Default Question Activated"
    redirect_to admin_default_questions_path
  end

  protected

  def collection
    @default_questions ||= end_of_association_chain.order('priority DESC, id DESC').paginate(:page => params[:page])
  end
end

app/views/admin/default_questions/_default_question.html.haml
%tr{:class => cycle('odd', 'even')}
  %td.priority= default_question.priority
  %td.question
    = link_to default_question.question_text, admin_default_question_path(default_question)
    - if default_question.featured?
      %sup Featured
  %td.qtype= Question::QUESTION_TYPES[default_question.question_type]
  %td.category= link_to default_question.category.name, admin_category_path(default_question.category)
  %td.questionnaire
    - if default_question.questionnaire
      = link_to(default_question.questionnaire.name, admin_questionnaire_path(default_question.questionnaire))
    - else
      None
  %td.active
    %small= default_question.active ? 'Active' : 'Inactive'
  %td.actions
    = image_tag 'admin/icons/tool.png', :class => 'tools', 'data-menu' => "#menu_default_question_#{default_question.id}"
    %ul[default_question, :menu]
      %li= link_to 'Show', admin_default_question_path(default_question), :class => 'show'
      %li= link_to 'Edit', edit_admin_default_question_path(default_question), :class => 'edit'
      %li
        - if default_question.active?
          = link_to 'Deactivate', deactivate_admin_default_question_path(default_question), :class => 'deactivate', :method => :put
        - else
          = link_to 'Activate', activate_admin_default_question_path(default_question), :class => 'activate', :method => :put

app/views/admin/default_questions/_form.html.haml
= semantic_form_for @default_question, :url => url do |f|
  = f.inputs do
    = f.input :priority
    = f.input :featured
    = f.input :category, :prompt => "Choose a category", :collection => Category.for_select
    = f.input :question_text, :as => :string, :label => "Question"
    = f.input :question_type, :as => :question_type, :label => "Answer Format"
    = f.input :questionnaire_id, :as => :hidden
    .clearer

  - cnt = 0
  #multiple_choice_answers.hidden
    #add_answers.quiet Add Answers
    #add_button= link_to image_tag("/assets/questions/plus_button.jpg"), '#'
    = f.inputs :class => "inputs multi_choice", :for => :default_multiple_choice_options do |g|
      - cnt += 1
      = g.input :answer_text, :as => :string, :label => "Answer ##{cnt}", :wrapper_html => {:class => 'mchoice'}

  = f.actions do
    - if @default_question.new_record?
      = f.action :submit, :label => "Create Default Question"
    - else
      = f.action :submit, :label => "Edit Default Question"

app/views/admin/default_questions/edit.html.haml
= content_for :side_menu do
  %ol.nav
    %li
      = link_to "&laquo; All Questions".html_safe, admin_default_questions_path
      = link_to "&laquo; This Question".html_safe, admin_default_question_path(@default_question)

%h1 Edit Default Question

= render :partial => "form", :locals => {:url => admin_default_question_path(@default_question)}

- content_for :extra_javascripts do
  = javascript_include_tag 'admin/questions'

app/views/admin/default_questions/index.html.haml
= content_for :side_menu do
  %ol.nav
    %li
      = link_to "New Question &raquo;".html_safe, new_admin_default_question_path

%h1
  CritiqueMe Default Questions

%table.merchants.smoothness.highlighter
  %thead
    %tr
      %th Priority
      %th Question
      %th Type
      %th Category
      %th Questionnaire
      %th &nbsp;
      %th &nbsp;
  %tfoot
    %tr
      %td{:colspan => 7}
        = will_paginate
  %tbody
    - if @default_questions.empty?
      %tr
        %td{:colspan => 7}
          %em No default questions found.
    - else
      = render @default_questions

app/views/admin/default_questions/new.html.haml
%h1 Create a New Default Question

= render :partial => "form", :locals => {:url => admin_default_questions_path}

- content_for :extra_javascripts do
  = javascript_include_tag 'admin/questions'

app/views/admin/default_questions/show.html.haml
= content_for :side_menu do
  %ol.nav
    %li
      = link_to "&laquo; All Questions".html_safe, admin_default_questions_path
      = link_to "Edit Question &raquo;".html_safe, edit_admin_default_question_path(@default_question)
      - if @default_question.active?
        = link_to "Deactivate &raquo;".html_safe, deactivate_admin_default_question_path(@default_question), :method => :put
      - else
        = link_to "Activate &raquo;".html_safe, activate_admin_default_question_path(@default_question), :method => :put

%h1 Show Default Question

%ul.show_page
  %li
    %label Priority:
    %p= @default_question.priority
    .clear
  %li
    %label Featured?
    %p= @default_question.featured?
    .clear
  %li
    %label Category:
    %p
      - if @default_question.category
        = link_to @default_question.category.name, admin_category_path(@default_question.category)
      - else
        None
    .clear
  %li
    %label Question Text:
    %p= @default_question.question_text
    .clear
  %li
    %label Question Type:
    %p= Question::QUESTION_TYPES[@default_question.question_type]
    .clear
  - if @default_question.questionnaire_id
    %li
      %label Questionnaire
      %p= link_to @default_question.questionnaire.name, admin_questionnaire_path(@default_question.questionnaire)
      .clear
  - if Question::QUESTION_TYPES[@default_question.question_type] == :multiple_choice
    %li
      %label Multiple Choice Options:
      %p
        - @default_question.default_multiple_choice_options.each_with_index do |mco, i|
          = "#{i+1}) #{mco.answer_text}"
          %br
      .clear
  %li
    %label Active?:
    %p= @default_question.active ? "Active" : "Inactive"
    .clear